"""product master, vendor mapping, vendor rating

Revision ID: 20b99d75676e
Revises: 3b8e09942e47
Create Date: 2026-09-22 14:27:40.202004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b99d75676e'
down_revision: Union[str, None] = '3b8e09942e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('procurement_type', sa.Enum('ITEM', 'ASSET', 'SERVICE', name='procurementtype'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('type_specific_attrs', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_master_code'), 'product_master', ['code'], unique=True)
    op.create_table('vendor_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('price_competitiveness', sa.Float(), nullable=False),
    sa.Column('on_time_pct', sa.Float(), nullable=True),
    sa.Column('quality_pct', sa.Float(), nullable=True),
    sa.Column('compliance_pct', sa.Float(), nullable=True),
    sa.Column('responsiveness', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('last_manual_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=True),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['vendor_ratings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('product_master_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='mappingstate'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['product_master_id'], ['product_master.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'product_master_id', name='uq_vendor_product')
    )
    op.create_table('vendor_mapping_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='mappingstate'), nullable=True),
    sa.Column('to_state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='mappingstate'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['vendor_mappings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_mapping_history')
    op.drop_table('vendor_mappings')
    op.drop_table('rating_history')
    op.drop_table('vendor_ratings')
    op.drop_index(op.f('ix_product_master_code'), table_name='product_master')
    op.drop_table('product_master')
    # ### end Alembic commands ###
