"""tenders, line items, invites, approval rounds, approval bands

Revision ID: 37021e8048a1
Revises: 20b99d75676e
Create Date: 2026-09-22 14:40:53.766836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37021e8048a1'
down_revision: Union[str, None] = '20b99d75676e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tender_type', sa.Enum('RFQ', 'RFP', 'RATE_CONTRACT', name='tendertype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'WITHDRAWN', name='tenderstatus'), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('min_rating_threshold', sa.Float(), nullable=False),
    sa.Column('min_invites', sa.Integer(), nullable=True),
    sa.Column('max_invites', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('consecutive_rejections', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_approval_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='rounddecision'), nullable=False),
    sa.Column('required_tier', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user_accounts.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('product_master_id', sa.Integer(), nullable=False),
    sa.Column('procurement_type', sa.Enum('ITEM', 'ASSET', 'SERVICE', name='procurementtype'), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('split_award_allowed', sa.Boolean(), nullable=False),
    sa.Column('min_rating_threshold_override', sa.Float(), nullable=True),
    sa.Column('technical_eval_method', sa.Enum('QUALIFY_DISQUALIFY', 'SCORED', 'QCBS', name='technicalevalmethod'), nullable=False),
    sa.Column('technical_weight', sa.Float(), nullable=True),
    sa.Column('price_weight', sa.Float(), nullable=True),
    sa.Column('line_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_master_id'], ['product_master.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_line_item_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rating_at_resolution', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tender_line_item_id'], ['tender_line_items.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_line_item_id', 'vendor_id', name='uq_invite_line_vendor')
    )
    op.add_column('user_accounts', sa.Column('approval_tier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'approval_tier')
    op.drop_table('tender_invites')
    op.drop_table('tender_line_items')
    op.drop_table('tender_approval_rounds')
    op.drop_table('tenders')
    op.drop_table('approval_bands')
    # ### end Alembic commands ###
