"""other required documents

Revision ID: 37e3f4c7b505
Revises: b29c49526ec2
Create Date: 2026-09-24 17:00:27.143833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e3f4c7b505'
down_revision: Union[str, None] = 'b29c49526ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE vendordoctype ADD VALUE IF NOT EXISTS 'OTHER'")
    op.add_column('vendor_documents', sa.Column('custom_label', sa.String(), nullable=False, server_default=''))
    op.drop_constraint('uq_vendor_doctype', 'vendor_documents', type_='unique')
    op.create_unique_constraint('uq_vendor_doctype_label', 'vendor_documents', ['vendor_id', 'doc_type', 'custom_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_doctype_label', 'vendor_documents', type_='unique')
    op.create_unique_constraint('uq_vendor_doctype', 'vendor_documents', ['vendor_id', 'doc_type'])
    op.drop_column('vendor_documents', 'custom_label')
    # ### end Alembic commands ###
