"""unique vendor email phone pan

Revision ID: 9c8a97ab95c7
Revises: 5452d1cd3b9a
Create Date: 2026-09-24 12:52:27.480089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8a97ab95c7'
down_revision: Union[str, None] = '5452d1cd3b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vendors_email', 'vendors', ['email'])
    op.create_unique_constraint('uq_vendors_pan', 'vendors', ['pan'])
    op.create_unique_constraint('uq_vendors_phone', 'vendors', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    for col in ('phone', 'pan', 'email'):
        op.drop_constraint(f'uq_vendors_{col}', 'vendors', type_='unique')
