"""required vendor documents on products and categories

Revision ID: b29c49526ec2
Revises: c5da3555e62d
Create Date: 2026-09-24 16:52:22.385308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29c49526ec2'
down_revision: Union[str, None] = 'c5da3555e62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('required_documents', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('product_master', sa.Column('required_documents', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_master', 'required_documents')
    op.drop_column('product_categories', 'required_documents')
    # ### end Alembic commands ###
