"""vendor registration fields and document types

Revision ID: c5da3555e62d
Revises: e13852848f92
Create Date: 2026-09-24 16:45:06.847340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5da3555e62d'
down_revision: Union[str, None] = 'e13852848f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE vendordoctype ADD VALUE IF NOT EXISTS 'BUSINESS_LICENSE'")
    op.execute("ALTER TYPE vendordoctype ADD VALUE IF NOT EXISTS 'DRUG_LICENSE'")
    op.execute("ALTER TYPE vendordoctype ADD VALUE IF NOT EXISTS 'MSME_UDYAM'")
    op.execute("ALTER TYPE vendordoctype ADD VALUE IF NOT EXISTS 'ISO_CERTIFICATE'")
    op.execute("ALTER TYPE vendordoctype ADD VALUE IF NOT EXISTS 'SAMPLE_CATALOG'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('trade_name', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('year_of_incorporation', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('registered_address', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('branch_locations', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('bank_ifsc', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('contact_designation', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('escalation_contact_name', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('escalation_contact_phone', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('escalation_contact_email', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('delivery_lead_time_days', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('min_order_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'min_order_value')
    op.drop_column('vendors', 'delivery_lead_time_days')
    op.drop_column('vendors', 'payment_terms')
    op.drop_column('vendors', 'escalation_contact_email')
    op.drop_column('vendors', 'escalation_contact_phone')
    op.drop_column('vendors', 'escalation_contact_name')
    op.drop_column('vendors', 'contact_designation')
    op.drop_column('vendors', 'bank_ifsc')
    op.drop_column('vendors', 'bank_account_number')
    op.drop_column('vendors', 'bank_name')
    op.drop_column('vendors', 'branch_locations')
    op.drop_column('vendors', 'registered_address')
    op.drop_column('vendors', 'year_of_incorporation')
    op.drop_column('vendors', 'entity_type')
    op.drop_column('vendors', 'trade_name')
    # ### end Alembic commands ###
    # PostgreSQL can't drop enum values; the new vendordoctype values stay in the type.
