"""vendor document valid till

Revision ID: e13852848f92
Revises: 011fb2924623
Create Date: 2026-09-24 16:37:36.144246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13852848f92'
down_revision: Union[str, None] = '011fb2924623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_documents', sa.Column('valid_till', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_documents', 'valid_till')
    # ### end Alembic commands ###
